backend/views/RecommendationView.py
from http import HTTPStatus
from backend.models import db
from flask import json, render_template, request, redirect, Blueprint, Response
from ..models.UserCityModel import UserCityModel

recommendBlueprint = Blueprint('recommend', __name__, url_prefix='')


@recommendBlueprint.route('/recommend', methods=['GET'])
def recommendInput():
    return render_template("recommend.html")

backend/views/UserCityView.py
from http import HTTPStatus
from backend.models import db
from flask import json, render_template, request, redirect, Blueprint, Response

from backend.models.UserCityModel import UserCityModel
from ..models.DestinationModel import DestinationModel

userCityBlueprint = Blueprint('usercity', __name__, url_prefix='')


@userCityBlueprint.route('/ratings', methods=['GET'])
def getRatings():
    # if request.method == "POST":
    #     destination = request.form["content"]
    #     new_destination = DestinationModel(data=destination)
    # print(db)
    # print(new_destination)

    # try:
    #     db.session.add(new_destination)
    #     db.session.commit()
    #     return redirect("/")
    # except:
    #     return "There was an issiue adding your task"

    destinations = UserCityModel.query.limit(10).all()
    return render_template("userCity.html", destinations=destinations)
    # for destination in destinations:
    #     print(destination.id)

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <!-- jinja2 syntax(flask) -->
    {% block head%}{% endblock %} 
</head>
<body>
    {% block body%}{% endblock %} 
</body>
</html>

backend/templates/form.html
{% block content %}
<div class="formwrapper">
    <form method="POST">
        <div class="city">
            {{ form.city(placeholder='city') }} {{ form.name.label }}
        </div>
        <div class="submitbutton">
            <input id="submit" type="submit" value="Submit">
        </div>
    </form>
</div>

backend/templates/index.html
{% extends "bootstrap/base.html" %}
{% block title %}Awesome Recommender{% endblock %}

{% block navbar %}
<div class="navbar navbar-fixed-top">
  <!-- ... -->
</div>
{% endblock %}

{% block content %}
  <h1>Recommender</h1>
  <div>
    <a href="{{ url_for('recommend.recommendInput')}}">recommend</a>
    <a href="{{ url_for('usercity.getRatings') }}">list of visits</a>
    </div>
{% endblock %}

backend/templates/recommend.html
{% extends "bootstrap/base.html" %}
{% block title %}Awesome Recommender{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{ url_for('static', filename='css/recommend.css') }}">

{% endblock %}

{% block scripts %}
{{super()}}
<script src="{{ url_for('static', filename='js/autocomplete.js') }}"></script>
<script src="{{ url_for('static', filename='js/general.js') }}"></script>

{% endblock %}

{% block content %}
<h1 class="display-4">Travel destinations recommendations</h1>
{% if not results %}
<p>Enter cities that you've been to and liked</p>
<form action="/recommend/results" method="POST" autocomplete="off">
    <div class='col-xs-12 col-sm-12 col-md-10 col-lg-10'>
        <div class='input-group' , id='first'>
            <input class="autocomplete" class='form-control' type='text' name='city_name' placeholder="Enter a city"/>
        </div>
        <button type="submit" id="submit" value="submit" class="btn btn-light">Get recommendations</button>

    </div>
</form>
{% endif %}

{% if results %}
<p>Input: {{cities}}</p>
<div class="info">
    <iframe class="info_inside"
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3309.3312622412445!2d-83.37737678492407!3d33.958324180631536!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88f66cdecc8d0783%3A0x4f152e9d93fa5d6!2s170+College+Ave%2C+Athens%2C+GA+30601%2C+USA!5e0!3m2!1sen!2sie!4v1464026910465"
             frameborder="0" style="border:0">
    </iframe>
</div>
{% for key, value in results.items() %}
<div class="col-xs-6">
    <h2 class="sub-header">{{key}}</h2>
    <div class="table-responsive"></div>
    <table class="table table-striped">
        <thead>
        <th>City</th>
        <th>Because you liked</th>
        </thead>
        {% for val in value %}
        <tr>
            <td><a href="https://www.google.com/search?q={{ val[0] }}" target="_blank" onmouseover="showInfo('{{val[0]}}')">{{val[0]}}</a></td>
            <td>{{val[2]}}</td>
            <td>
                <button type="button" onclick="sendLike(this, '{{key}}')">+1</button>
                <button type="button" onclick="sendDislike(this, '{{key}}')">-1</button>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
</div>
{% endfor %}


{% endif %}
{% endblock %}

backend/templates/update.html
{% extends 'base.html' %}

{% block head%}
<title>Task Master</title>
{% endblock %}

{% block body%}
<div class="content">
    <h1>Update Task</h1>
    <form action="/update/{{task.id}}" method="POST">
        <input type="text" name="content" id="content" value="{{task.content}}">
        <input type="submit" value="Update">
    </form>
</div>
{% endblock %}

backend/templates/userCity.html
{% extends 'base.html' %}

{% block head%}
<title>Recommneder</title>
{% endblock %}

{% block body%}
{% if destinations|length < 1 %}
<p>There are no Destinations</p>
{% else %}
<div>
    <table>
        <tr>
            <th>id</th>
            <th>user</th>
            <th>city</th>
            <th>number of visits</th>
        </tr>
        {% for i in range(destinations|length) %}
            <tr>
                <td>{{destinations[i].id}}</td>
                <td>{{destinations[i].user}}</td>
                <td>{{destinations[i].city}}</td>
                <td>{{destinations[i].number_of_visits}}</td>
                
            </tr>
        {% endfor %}

    </table>
</div>
{% endif %}
<form action="/ratings" method="GET">
    <input type="text" name="content" id="content">
    <input type="submit" value="Inser destination">
</form>

{% endblock %}